version: '2'
services:
  myproject:
    build: ./
    container_name: Laravel-Web
    restart: always
    volumes:
      - ./code:/var/www/html
    ports:
      - 80:80
      - 81:8000
  db:
    image: mysql:8.0
    container_name: db-laravel
      environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: laravel-db
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      ports:
        - "6034:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: pma-laravel
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80